# Generated by Django 4.2 on 2023-05-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codCaixa', models.CharField(max_length=10)),
                ('dataCadastroCaixa', models.DateTimeField(auto_now_add=True)),
                ('qr_code_cx', models.ImageField(blank=True, upload_to='qrcodescx')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=200)),
                ('codCliente', models.CharField(max_length=10)),
                ('dataCadastroCliente', models.DateTimeField(auto_now_add=True)),
                ('qr_code_cl', models.ImageField(blank=True, upload_to='qrcodescl')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmprestimo', models.DateTimeField(auto_now_add=True)),
                ('idCaixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.caixa')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
            ],
        ),
    ]
